-- | homunc — Homun to Rust compiler
--
-- Usage:
--   homunc <input.hom>           # prints Rust to stdout
--   homunc <input.hom> -o <out>  # writes to file
--   homunc --help
--
-- Pipeline:
--   Source text
--     └─► Lexer   (Lexer.hs)   → [Token]
--     └─► Parser  (Parser.hs)  → Program (AST)
--     └─► Sema    (Sema.hs)    → Checked/annotated Program
--     └─► Codegen (Codegen.hs) → Rust source text
--
module Main where

import System.Environment (getArgs)
import System.Exit        (exitFailure, exitSuccess)
import System.IO          (hPutStrLn, stderr, writeFile)
import Data.List          (intercalate)

import Lexer    (lexHomun)
import Parser   (parseHomun)
import Sema     (analyzeProgram)
import Codegen  (codegenProgram)

-- ─────────────────────────────────────────
-- Main
-- ─────────────────────────────────────────

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help"] -> printHelp >> exitSuccess
    [src]      -> compileToStdout src
    [src, "-o", out] -> compileToFile src out
    _          -> do
      hPutStrLn stderr "Usage: homunc <input.hom> [-o output.rs]"
      exitFailure

printHelp :: IO ()
printHelp = mapM_ putStrLn
  [ "homunc — Homun to Rust compiler"
  , ""
  , "USAGE:"
  , "  homunc <input.hom>            Compile and print Rust to stdout"
  , "  homunc <input.hom> -o out.rs  Compile and write to file"
  , "  homunc --help                 Show this message"
  , ""
  , "PIPELINE:"
  , "  .hom source  →  Lexer  →  Parser  →  Sema  →  Codegen  →  .rs"
  , ""
  , "LANGUAGE FEATURES SUPPORTED:"
  , "  • Variable bindings      x := 10"
  , "  • Lambdas                fn := (a, b) -> { a + b }"
  , "  • Typed params           fn := (a: int, b: int) -> int { a + b }"
  , "  • Recursion              fib := (n) -> { if ... { fib(n-1) + fib(n-2) } }"
  , "  • Pipe operator          list | filter(f) | map(g)"
  , "  • Collections            @[], @{}, @()"
  , "  • Pattern match          match x { ... }"
  , "  • if/else, for, while"
  , "  • break => value         for ... do { break => val }"
  , "  • Structs & Enums"
  , "  • String interpolation   \"Hello ${name}\""
  , "  • RON load/save"
  ]

-- ─────────────────────────────────────────
-- Compile pipeline
-- ─────────────────────────────────────────

compile :: String -> String -> Either String String
compile filename source = do
  -- 1. Lex
  tokens <- mapErr "Lex error" $ lexHomun source

  -- 2. Parse
  ast    <- mapErr "Parse error" $ parseHomun tokens

  -- 3. Semantic analysis
  ast'   <- mapErr "Semantic errors" $ case analyzeProgram ast of
              Left errs -> Left (intercalate "\n" (map show errs))
              Right p   -> Right p

  -- 4. Code generation
  let rustSrc = preamble ++ "\n" ++ codegenProgram ast'

  return rustSrc

mapErr :: String -> Either String a -> Either String a
mapErr prefix (Left e)  = Left (prefix ++ ": " ++ e)
mapErr _ (Right a)       = Right a

compileToStdout :: FilePath -> IO ()
compileToStdout path = do
  src <- readFile path
  case compile path src of
    Left err  -> hPutStrLn stderr err >> exitFailure
    Right out -> putStr out

compileToFile :: FilePath -> FilePath -> IO ()
compileToFile src out = do
  source <- readFile src
  case compile src source of
    Left err   -> hPutStrLn stderr err >> exitFailure
    Right code -> do
      writeFile out code
      putStrLn $ "Compiled " ++ src ++ " → " ++ out

-- ─────────────────────────────────────────
-- Rust preamble: runtime support helpers
-- ─────────────────────────────────────────

preamble :: String
preamble = unlines
  [ "// ============================================================"
  , "// Generated by homunc — Homun to Rust compiler"
  , "// DO NOT EDIT MANUALLY"
  , "// ============================================================"
  , ""
  , "#![allow(unused_variables, unused_mut, dead_code, unused_imports)]"
  , "#![allow(non_snake_case)]"
  , ""
  , "use std::collections::{HashMap, HashSet};"
  , ""
  , "// ── Homun runtime helpers ────────────────────────────────────"
  , ""
  , "/// Python-style slice helper"
  , "pub fn homun_slice<T: Clone>(v: &Vec<T>, start: i64, end: i64, step: i64) -> Vec<T> {"
  , "    let len = v.len() as i64;"
  , "    let norm = |i: i64| -> usize {"
  , "        let i = if i < 0 { len + i } else { i };"
  , "        i.max(0).min(len) as usize"
  , "    };"
  , "    let s = norm(start);"
  , "    let e = norm(end);"
  , "    if step > 0 {"
  , "        (s..e).step_by(step as usize).map(|i| v[i].clone()).collect()"
  , "    } else if step < 0 {"
  , "        let s2 = if end   == i64::MAX { 0 } else { norm(end) };"
  , "        let e2 = if start == 0        { len as usize } else { norm(start) };"
  , "        (s2..e2).rev().step_by((-step) as usize).map(|i| v[i].clone()).collect()"
  , "    } else {"
  , "        vec![]"
  , "    }"
  , "}"
  , ""
  , "/// Homun `len` — works on Vec, HashMap, HashSet, String"
  , "pub fn len<C: HomunLen>(c: &C) -> i32 { c.homun_len() as i32 }"
  , ""
  , "pub trait HomunLen { fn homun_len(&self) -> usize; }"
  , "impl<T> HomunLen for Vec<T>    { fn homun_len(&self) -> usize { self.len() } }"
  , "impl<K,V> HomunLen for HashMap<K,V> { fn homun_len(&self) -> usize { self.len() } }"
  , "impl<T> HomunLen for HashSet<T> { fn homun_len(&self) -> usize { self.len() } }"
  , "impl HomunLen for String        { fn homun_len(&self) -> usize { self.len() } }"
  , "impl HomunLen for str           { fn homun_len(&self) -> usize { self.len() } }"
  , ""
  , "/// Homun `str()` — convert to String"
  , "pub fn str_of<T: std::fmt::Display>(x: T) -> String { x.to_string() }"
  , ""
  , "/// Homun `range`"
  , "pub fn range(n: i32) -> std::ops::Range<i32> { 0..n }"
  , "pub fn range2(start: i32, end_: i32) -> std::ops::Range<i32> { start..end_ }"
  , "pub fn range3(start: i32, end_: i32, step: i32)"
  , "    -> impl Iterator<Item = i32>"
  , "{"
  , "    let mut i = start;"
  , "    std::iter::from_fn(move || {"
  , "        if (step > 0 && i < end_) || (step < 0 && i > end_) {"
  , "            let cur = i; i += step; Some(cur)"
  , "        } else { None }"
  , "    })"
  , "}"
  , ""
  , "/// Homun `filter` (mirrors Python-style pipe usage)"
  , "pub fn filter<T: Clone, F: Fn(T) -> bool>(v: &[T], f: F) -> Vec<T> {"
  , "    v.iter().cloned().filter(|x| f(x.clone())).collect()"
  , "}"
  , ""
  , "/// Homun `map`"
  , "pub fn map<T: Clone, U, F: Fn(T) -> U>(v: &[T], f: F) -> Vec<U> {"
  , "    v.iter().cloned().map(f).collect()"
  , "}"
  , ""
  , "/// Homun `reduce`"
  , "pub fn reduce<T: Clone, F: Fn(T, T) -> T>(v: Vec<T>, f: F) -> Option<T> {"
  , "    v.into_iter().reduce(f)"
  , "}"
  , ""
  , "/// Homun `+` on Vec — concatenate two vectors"
  , "pub fn homun_concat<T>(mut a: Vec<T>, b: Vec<T>) -> Vec<T> {"
  , "    a.extend(b);"
  , "    a"
  , "}"
  , ""
  , "/// Homun indexing — works on Vec (by i32) and HashMap (by key)"
  , "pub trait HomunIndex<K> {"
  , "    type Output;"
  , "    fn homun_idx(&self, key: K) -> Self::Output;"
  , "}"
  , ""
  , "impl<T: Clone> HomunIndex<i32> for Vec<T> {"
  , "    type Output = T;"
  , "    fn homun_idx(&self, key: i32) -> T {"
  , "        self[if key < 0 { self.len() as i32 + key } else { key } as usize].clone()"
  , "    }"
  , "}"
  , ""
  , "impl<V: Clone> HomunIndex<i32> for HashMap<i32, V> {"
  , "    type Output = V;"
  , "    fn homun_idx(&self, key: i32) -> V { self[&key].clone() }"
  , "}"
  , ""
  , "impl<V: Clone> HomunIndex<&str> for HashMap<String, V> {"
  , "    type Output = V;"
  , "    fn homun_idx(&self, key: &str) -> V { self[key].clone() }"
  , "}"
  , ""
  , "// ─────────────────────────────────────────────────────────────"
  ]
