// main_imp.rs — I/O and process helpers for main.hom.
//
// Importing this file via `use main_imp` in main.hom sets has_rs_dep=true
// in the homunc sema checker, disabling undefined-reference checks for dep/*
// functions and runtime functions that are available at include!() time in
// lib.rs but unknown to homunc's static checker.
//
// Helpers:
//   read_stdin()              -> String
//   write_file(path, content) -> ()
//   exit_process(code)        -> !
//   get_args()                -> Vec<String>
//   preamble()                -> String

/// Read all of stdin to a String. Panics on I/O error.
pub fn read_stdin() -> String {
    use std::io::Read;
    let mut s = String::new();
    std::io::stdin()
        .read_to_string(&mut s)
        .expect("Failed to read stdin");
    s
}

/// Write content to a file. Exits on I/O error.
pub fn write_file(path: String, content: String) {
    std::fs::write(&path, &content).unwrap_or_else(|e| {
        eprintln!("Cannot write {}: {}", path, e);
        std::process::exit(1);
    });
}

/// Exit the process with the given exit code.
/// Named exit_process to avoid collision with std::process::exit in scope.
pub fn exit_process(code: i32) -> ! {
    std::process::exit(code)
}

/// Return command-line arguments (skipping the program name) as Vec<String>.
pub fn get_args() -> Vec<String> {
    std::env::args().skip(1).collect()
}

/// Return the standard preamble string prepended to compiled output.
pub fn preamble() -> String {
    format!(
        "// Generated by homunc — Homun to Rust compiler\n\
         \n\
         #![allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros)]\n\
         #![allow(non_snake_case)]\n\
         \n\
         // ── builtin ────────────────────────────────────────────────\n\
         {}\n",
        include_str!("hom/builtin.rs")
    )
}
