/// homunc — Homun to Rust compiler
///
/// Usage:
///   homunc <input.hom>           # prints Rust to stdout
///   homunc <input.hom> -o <out>  # writes to file
///   homunc --help
///
/// Pipeline:
///   Source text
///     -> Lexer   (lexer.rs)   -> Vec<Token>
///     -> Parser  (parser.rs)  -> Program (AST)
///     -> Sema    (sema.rs)    -> Checked Program
///     -> Codegen (codegen.rs) -> Rust source text
#[allow(dead_code)]
mod ast;
mod codegen;
#[allow(dead_code)]
mod lexer;
mod parser;
mod sema;

use std::env;
use std::fs;
use std::io::{self, Read};
use std::process;

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    match args.as_slice() {
        [flag] if flag == "--help" => {
            print_help();
        }
        [] => {
            compile_from_stdin();
        }
        [src] => {
            compile_to_stdout(src);
        }
        [src, flag, out] if flag == "-o" => {
            compile_to_file(src, out);
        }
        _ => {
            eprintln!("Usage: homunc [input.hom] [-o output.rs]");
            process::exit(1);
        }
    }
}

fn print_help() {
    println!("homunc — Homun to Rust compiler");
    println!();
    println!("USAGE:");
    println!("  homunc <input.hom>            Compile and print Rust to stdout");
    println!("  homunc <input.hom> -o out.rs  Compile and write to file");
    println!("  homunc --help                 Show this message");
    println!();
    println!("PIPELINE:");
    println!("  .hom source  ->  Lexer  ->  Parser  ->  Sema  ->  Codegen  ->  .rs");
    println!();
    println!("LANGUAGE FEATURES SUPPORTED:");
    println!("  * Variable bindings      x := 10");
    println!("  * Lambdas                fn := (a, b) -> {{ a + b }}");
    println!("  * Typed params           fn := (a: int, b: int) -> int {{ a + b }}");
    println!("  * Recursion              fib := (n) -> {{ if ... {{ fib(n-1) + fib(n-2) }} }}");
    println!("  * Pipe operator          list | filter(f) | map(g)");
    println!("  * Collections            @[], @{{}}, @()");
    println!("  * Pattern match          match x {{ ... }}");
    println!("  * if/else, for, while");
    println!("  * break => value         for ... do {{ break => val }}");
    println!("  * Structs & Enums");
    println!("  * String interpolation   \"Hello ${{name}}\"");
    println!("  * RON load/save");
}

fn compile(_filename: &str, source: &str) -> Result<String, String> {
    // 1. Lex
    let tokens = lexer::lex(source).map_err(|e| format!("Lex error: {}", e))?;

    // 2. Parse
    let ast = parser::parse(tokens).map_err(|e| format!("Parse error: {}", e))?;

    // 3. Semantic analysis
    sema::analyze_program(&ast).map_err(|errs| {
        let msgs: Vec<String> = errs.iter().map(|e| e.to_string()).collect();
        format!("Semantic errors:\n{}", msgs.join("\n"))
    })?;

    // 4. Code generation
    let rust_src = format!("{}\n{}", preamble(), codegen::codegen_program(&ast));
    Ok(rust_src)
}

fn compile_from_stdin() {
    let mut src = String::new();
    io::stdin()
        .read_to_string(&mut src)
        .expect("Failed to read stdin");
    match compile("<stdin>", &src) {
        Ok(out) => print!("{}", out),
        Err(e) => {
            eprintln!("{}", e);
            process::exit(1);
        }
    }
}

fn compile_to_stdout(path: &str) {
    let src = fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("Cannot read {}: {}", path, e);
        process::exit(1);
    });
    match compile(path, &src) {
        Ok(out) => print!("{}", out),
        Err(e) => {
            eprintln!("{}", e);
            process::exit(1);
        }
    }
}

fn compile_to_file(src: &str, out: &str) {
    let source = fs::read_to_string(src).unwrap_or_else(|e| {
        eprintln!("Cannot read {}: {}", src, e);
        process::exit(1);
    });
    match compile(src, &source) {
        Ok(code) => {
            fs::write(out, &code).unwrap_or_else(|e| {
                eprintln!("Cannot write {}: {}", out, e);
                process::exit(1);
            });
            println!("Compiled {} -> {}", src, out);
        }
        Err(e) => {
            eprintln!("{}", e);
            process::exit(1);
        }
    }
}

fn preamble() -> &'static str {
    "// Generated by homunc — Homun to Rust compiler\n\
     \n\
     #![allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros)]\n\
     #![allow(non_snake_case)]\n\
     \n\
     include!(\"builtin.rs\");\n"
}
