// main_imp.rs — I/O and process helpers for main.hom.
//
// Importing this file via `use main_imp` in main.hom sets has_rs_dep=true in
// the homunc sema checker, disabling undefined-reference checks for dep/*
// functions and runtime functions that are available at include!() time in
// lib.rs but unknown to homunc's static checker.
//
// I/O helpers:
//   read_stdin()              -> String
//   write_file(path, content) -> ()
//   exit_process(code)        -> !
//   get_args()                -> Vec<String>
//   preamble()                -> String
//   print_str, eprint_str, homunc_version, emit_runtime_fn
//   result_ok_or_exit(result) -> String
//
// Pipeline wrappers (expose compiler stages to main.hom):
//   lex(source)                              -> Result<Vec<Token>, String>
//   parse(tokens)                            -> Result<Vec<Stmt>, String>
//   sema_analyze_skip_undef(ast, imported)   -> Vec<String>
//   register_known_dep_fns()                 -> ()
//   codegen_program(ast, rs_content)         -> String
//   resolve(path)                            -> Result<ResolvedProgram, String>
//   resolve_module(path)                     -> Result<ResolvedProgram, String>
//   build_embed_map(ast)                     -> HashMap<String, String>

/// Read all of stdin to a String. Panics on I/O error.
pub fn read_stdin() -> String {
    use std::io::Read;
    let mut s = String::new();
    std::io::stdin()
        .read_to_string(&mut s)
        .expect("Failed to read stdin");
    s
}

/// Write content to a file. Exits on I/O error.
pub fn write_file(path: String, content: String) {
    std::fs::write(&path, &content).unwrap_or_else(|e| {
        eprintln!("Cannot write {}: {}", path, e);
        std::process::exit(1);
    });
}

/// Exit the process with the given exit code.
/// Named exit_process to avoid collision with std::process::exit in scope.
pub fn exit_process(code: i32) -> ! {
    std::process::exit(code)
}

/// Return command-line arguments (skipping the program name) as Vec<String>.
pub fn get_args() -> Vec<String> {
    std::env::args().skip(1).collect()
}

/// Return the standard preamble string prepended to compiled output.
/// Uses builtin_rs() instead of include_str!("hom/builtin.rs") so that the
/// path resolves correctly when this code is included inside the lib crate
/// (where include_str! would resolve relative to OUT_DIR, not src/).
pub fn preamble() -> String {
    format!(
        "// Generated by homunc — Homun to Rust compiler\n\
         \n\
         #![allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros)]\n\
         #![allow(non_snake_case)]\n\
         \n\
         // ── builtin ────────────────────────────────────────────────\n\
         {}\n",
        builtin_rs()
    )
}

/// Print a string to stdout without a trailing newline.
pub fn print_str(s: String) {
    print!("{}", s);
}

/// Print a string to stderr with a trailing newline.
pub fn eprint_str(s: String) {
    eprintln!("{}", s);
}

/// Return the compiler version string (set at build time via HOMUN_VERSION env).
pub fn homunc_version() -> String {
    env!("HOMUN_VERSION").to_string()
}

/// Emit the full embedded runtime (builtin + std + re + heap) to stdout.
/// Users of multi-module Cargo projects can call `homunc --emit-runtime > src/runtime.rs`
/// instead of needing the hom-std submodule.
pub fn emit_runtime_fn() {
    print!("{}", preamble());
    for name in &["std", "re", "heap", "chars", "str_ext", "dict", "path", "fs"] {
        if let Some(content) = embedded_rs(name) {
            println!("{}", content);
        }
    }
}

/// Extract the Ok value from a Result<String, String>.
/// On Err, prints the error to stderr and exits with code 1.
pub fn result_ok_or_exit(result: Result<String, String>) -> String {
    match result {
        Ok(s) => s,
        Err(e) => {
            eprintln!("{}", e);
            std::process::exit(1);
        }
    }
}

/// Return type of compile_source / compile_file: Ok(rust_code) or Err(message).
pub type CompileResult = Result<String, String>;

// ─── Pipeline wrappers — expose compiler stages to main.hom ──────────────────
// These thin functions let main.hom call each stage directly.
// All accept/return owned values matching Homun's clone-everything codegen.

pub fn lex(source: String) -> Result<Vec<crate::lexer_hom::Token>, String> {
    crate::lexer_hom::lex(source)
}

pub fn parse(tokens: Vec<crate::lexer_hom::Token>) -> Result<Vec<Stmt>, String> {
    crate::parser_hom::parse(tokens)
}

pub fn sema_analyze_skip_undef(ast: Vec<Stmt>, imported: Vec<String>) -> Vec<String> {
    crate::sema_hom::sema_analyze_skip_undef(ast, imported)
}

pub fn register_known_dep_fns() {
    crate::codegen_hom::register_known_dep_fns()
}

/// Call codegen_program_with_resolved with an empty HomFiles set.
/// Used by compile_source in main.hom (no .hom dep graph for stdin/source path).
pub fn codegen_program(
    ast: Vec<Stmt>,
    rs_content: std::collections::HashMap<String, String>,
) -> String {
    crate::codegen_hom::codegen_program_with_resolved(
        ast,
        std::collections::HashSet::new(),
        rs_content,
    )
}

pub fn resolve(path: String) -> crate::resolver_hom::ResolveProgramResult {
    crate::resolver_hom::resolve(path)
}

pub fn resolve_module(path: String) -> crate::resolver_hom::ResolveProgramResult {
    crate::resolver_hom::resolve_module(path)
}

/// Build the rs_content map: for each `use foo` in the AST where foo is an
/// embedded runtime module, store its Rust source. Kept in Rust for HashMap
/// insertion with string keys (Homun's index-assign only covers integer indices).
pub fn build_embed_map(ast: Vec<Stmt>) -> std::collections::HashMap<String, String> {
    let mut map = std::collections::HashMap::new();
    for stmt in &ast {
        if let Stmt::Use(path) = stmt {
            if path.len() == 1 {
                if let Some(content) = crate::embedded_rs(&path[0]) {
                    map.insert(path[0].clone(), content);
                }
            }
        }
    }
    map
}
